CREATE TABLE task (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    title           VARCHAR(100)    NOT NULL ,
    description     VARCHAR(1000),
    status          VARCHAR(20)     NOT NULL DEFAULT 'TODO',
    created_at      timestamp       WITH TIME ZONE    NOT NULL
);